version: '3'
services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_KEYSPACE=fiap
#Rabbit
  fiap-coelho:
    image: rabbitmq:3.13.1-management
    ports:
      - 5672:5672 
      - 15672:15672

#postgres
  postgres:
    image: "postgres:15.5-alpine"
    container_name: postgres_fiap_3soat_g53
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pedido,pagamento
    ports:
      - "5432:5432"
    networks:
      backend:
        ipv4_address: 172.34.0.2
    volumes:
      - ./build/volumes/postgres_data:/var/lib/postgresql/data
networks:
  backend:
    driver: bridge
    ipam:
     config:
       - subnet: 172.34.0.0/24
         gateway: 172.34.0.1
