spring:

  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_PASSWORD:guest}
    virtual-host: fcplheqi

  cassandra:
    schema-action: CREATE_IF_NOT_EXISTS
    local-datacenter: ${DATACENTER:datacenter1}
    keyspace-name: ${KEYSPACE:spring_cassandra}
    request:
      timeout: 10s
    connection:
      connect-timeout: 10s
      init-query-timeout: 10s


  jackson:
    serialization.FAIL_ON_EMPTY_BEANS: false # Não falhar na serialização de objetos sem propriedades

    serialization:
      indent-output: true
